# Generated by Django 3.0.7 on 2020-06-27 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_auto_20200626_1658'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='summury',
            new_name='summary',
        ),
    ]
